// Mock data for Student Club Management System

import { Club, Event, Notification, GalleryImage, User } from './types';

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'Tech Club',
    description: 'Exploring the latest in technology and innovation. We organize hackathons, tech talks, and workshops.',
    category: 'Technology',
    memberCount: 85,
    points: 450,
    headId: 'user2',
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    name: 'Drama Society',
    description: 'Bringing stories to life through theatrical performances and creative expression.',
    category: 'Arts',
    memberCount: 62,
    points: 380,
    headId: 'user3',
    createdAt: '2025-01-20',
  },
  {
    id: '3',
    name: 'Photography Club',
    description: 'Capturing moments and exploring the art of photography through workshops and exhibitions.',
    category: 'Arts',
    memberCount: 45,
    points: 320,
    headId: 'user4',
    createdAt: '2025-02-01',
  },
  {
    id: '4',
    name: 'Robotics Club',
    description: 'Building and programming robots for competitions and demonstrations.',
    category: 'Technology',
    memberCount: 38,
    points: 410,
    headId: 'user5',
    createdAt: '2025-02-10',
  },
  {
    id: '5',
    name: 'Music Society',
    description: 'Creating harmony through diverse musical performances and jam sessions.',
    category: 'Arts',
    memberCount: 72,
    points: 395,
    headId: 'user6',
    createdAt: '2025-02-15',
  },
  {
    id: '6',
    name: 'Environmental Club',
    description: 'Promoting sustainability and environmental awareness on campus.',
    category: 'Social',
    memberCount: 55,
    points: 290,
    headId: 'user7',
    createdAt: '2025-02-20',
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Annual Hackathon 2026',
    description: '24-hour coding marathon with exciting prizes and learning opportunities.',
    date: '2026-04-15',
    time: '09:00 AM',
    location: 'Engineering Building, Hall A',
    clubId: '1',
    clubName: 'Tech Club',
    status: 'approved',
    createdBy: 'user2',
    attendanceCount: 120,
  },
  {
    id: '2',
    title: 'Spring Musical Performance',
    description: 'A spectacular theatrical performance showcasing student talent.',
    date: '2026-03-22',
    time: '06:00 PM',
    location: 'University Auditorium',
    clubId: '2',
    clubName: 'Drama Society',
    status: 'approved',
    createdBy: 'user3',
  },
  {
    id: '3',
    title: 'Photography Workshop',
    description: 'Learn advanced photography techniques from professional photographers.',
    date: '2026-03-18',
    time: '02:00 PM',
    location: 'Arts Building, Room 301',
    clubId: '3',
    clubName: 'Photography Club',
    status: 'pending',
    createdBy: 'user4',
  },
  {
    id: '4',
    title: 'Robot Wars Competition',
    description: 'Inter-university robotics competition with exciting battles.',
    date: '2026-04-20',
    time: '10:00 AM',
    location: 'Sports Complex',
    clubId: '4',
    clubName: 'Robotics Club',
    status: 'pending',
    createdBy: 'user5',
  },
  {
    id: '5',
    title: 'Campus Cleanup Drive',
    description: 'Join us in making our campus greener and cleaner.',
    date: '2026-03-25',
    time: '08:00 AM',
    location: 'Central Lawn',
    clubId: '6',
    clubName: 'Environmental Club',
    status: 'approved',
    createdBy: 'user7',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'event_approval',
    title: 'Event Approved',
    message: 'Your event "Annual Hackathon 2026" has been approved by the administration.',
    read: false,
    createdAt: '2026-03-10T14:30:00',
  },
  {
    id: '2',
    type: 'event_reminder',
    title: 'Upcoming Event Reminder',
    message: 'Photography Workshop is scheduled for tomorrow at 2:00 PM.',
    read: false,
    createdAt: '2026-03-17T09:00:00',
  },
  {
    id: '3',
    type: 'announcement',
    title: 'System Maintenance',
    message: 'The system will undergo maintenance on March 20th from 2:00 AM to 4:00 AM.',
    read: true,
    createdAt: '2026-03-09T10:00:00',
  },
  {
    id: '4',
    type: 'event_approval',
    title: 'Event Pending Review',
    message: 'Your event "Robot Wars Competition" is pending admin approval.',
    read: false,
    createdAt: '2026-03-11T11:20:00',
  },
];

export const mockGalleryImages: GalleryImage[] = [
  {
    id: '1',
    eventId: '1',
    eventName: 'Annual Hackathon 2026',
    url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800',
    uploadedAt: '2026-03-01',
  },
  {
    id: '2',
    eventId: '1',
    eventName: 'Annual Hackathon 2026',
    url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800',
    uploadedAt: '2026-03-01',
  },
  {
    id: '3',
    eventId: '2',
    eventName: 'Spring Musical Performance',
    url: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
    uploadedAt: '2026-02-28',
  },
  {
    id: '4',
    eventId: '3',
    eventName: 'Photography Workshop',
    url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800',
    uploadedAt: '2026-02-25',
  },
  {
    id: '5',
    eventId: '2',
    eventName: 'Spring Musical Performance',
    url: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=800',
    uploadedAt: '2026-02-28',
  },
  {
    id: '6',
    eventId: '1',
    eventName: 'Annual Hackathon 2026',
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
    uploadedAt: '2026-03-01',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Admin User',
    email: 'admin@university.edu',
    role: 'admin',
  },
  {
    id: 'user2',
    name: 'John Smith',
    email: 'john@university.edu',
    role: 'club_head',
    clubId: '1',
  },
  {
    id: 'user3',
    name: 'Emily Johnson',
    email: 'emily@university.edu',
    role: 'club_head',
    clubId: '2',
  },
  {
    id: 'user4',
    name: 'Michael Brown',
    email: 'michael@university.edu',
    role: 'student',
    clubId: '3',
  },
];
